services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
      - /mnt/e/ai/ws_project/data:/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    depends_on:
      - ollama
      - pipelines

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /mnt/e/ai/ws_project/ollama_models:/root/.ollama
      - /mnt/e/ai/ws_project/data:/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  pipelines:
    # Use the official, pre-built image
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - ./pipelines/custom_pipelines:/app/pipelines
    ports:
      - "9099:9099"
    environment:
      - PIPELINES_API_KEY=0p3n-w3bu!
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: always
    depends_on:
      - ollama

volumes:
  open-webui-data: {}